markdown: kramdown
highlighter: rouge
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : "0x74696d"
production_url : http://tgross.github.io
description: "T-Minus 15.193792102158E+9 years until the universe closes!"
author :
  name : Tim Gross
  github : tgross
  twitter : "0x74696d"
  email: "tim+blog@0x74696d.com"
